name: Main CI Develop

on: 
 push:
   branches: [ main ]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run sample script
        run: echo start running

  lint_job:
    uses: ./.github/workflows/job-lint.yml

  build_job:
    uses: ./.github/workflows/job-build-apk.yml

  sonar_job:
    uses: ./.github/workflows/job-sonar-analysis.yml



